ARDUINO_DIR  = /home/toni/temp/arduino
TARGET       = ADK
ARDUINO_LIBS = 
MCU          = atmega328p
F_CPU        = 16000000
ARDUINO_PORT = /dev/ttyACM3
AVRDUDE_ARD_BAUDRATE=115200
AVRDUDE_ARD_PROGRAMMER=arduino

include /usr/share/arduino/Arduino.mk
